# Generated by Django 4.2.20 on 2025-09-25 08:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='backup', max_length=255)),
                ('backup_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_logo', models.ImageField(blank=True, default='business-logo/logo.png', upload_to='business-logo')),
                ('business_name', models.CharField(default='Business Name', max_length=100)),
                ('business_address', models.CharField(blank=True, default='123 Main Street, Gweru', max_length=255)),
                ('business_email', models.EmailField(blank=True, default='example@mailanator.com', max_length=254, null=True, unique=True)),
                ('business_number', models.CharField(blank=True, default='+263123456789', max_length=20)),
                ('business_website', models.URLField(blank=True, default='businesssite.co.zw', max_length=100)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('currency_symbol', models.CharField(default='$', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Business Details',
            },
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_format', models.CharField(choices=[('%Y-%m-%d', 'YYYY-DD-MM'), ('%m/%d/%Y', 'MM/DD/YYYY'), ('%d/%m/%Y', 'DD/MM/YYYY'), ('%b %d, %Y', 'Month DD, YYYY'), ('%B %d, %Y', 'Full month DD, YYYY')], default='%Y-%m-%d', max_length=100)),
                ('timezone', models.CharField(choices=[('Africa/Harare', 'Africa/Harare'), ('Africa/Cairo', 'Africa/Cairo'), ('Europe/London', 'Europe/London'), ('Europe/Paris', 'Europe/Paris')], default='Africa/Harare', max_length=50)),
                ('backup_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('theme_color', models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('purple', 'Purple'), ('gold', 'Gold')], default='blue', max_length=20)),
                ('auto_backup', models.BooleanField(default=False)),
                ('dark_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'General Settings',
            },
        ),
        migrations.CreateModel(
            name='ReceiptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_logo', models.BooleanField(default=True)),
                ('show_thank_you_note', models.BooleanField(default=True)),
                ('thank_you_note', models.CharField(blank=True, default='Thank you for your purchase!', max_length=255)),
                ('show_cashier_name', models.BooleanField(default=True)),
                ('show_sales_time', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30)),
                ('allow_multiple_logins', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='profile/profile_1.jpg', upload_to='profile')),
                ('daily_report_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alerts_email', models.BooleanField(default=True)),
                ('low_stock_alerts', models.BooleanField(default=True)),
                ('expense_alerts', models.BooleanField(default=True)),
                ('enable_daily_reports', models.BooleanField(default=True)),
                ('enable_alert_emails', models.BooleanField(default=True)),
                ('enable_backup_notifications', models.BooleanField(default=True)),
                ('backup_retention_days', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
